export const INIT_CART = 'INIT_CART'
export const ADD_GOODS_CART = 'ADD_GOODS_CART'
export const EDIT_GOODS_CART = 'EDIT_GOODS_CART'
export const EDIT_ALL_GOODS_CART = 'EDIT_ALL_GOODS_CART'
export const DELETE_GOODS_CART = 'DELETE_GOODS_CART'

export const ADD_ADDRESS = 'ADD_ADDRESS'
export const EDIT_ADDRESS = 'EDIT_ADDRESS'
export const EDIT_ALL_ADDRESS = 'EDIT_ADDRESS'

export const ADD_ORDER = 'ADD_ORDER'
export const EDIT_ORDER_STATUS = 'EDIT_ORDER_STATUS'
export const EDIT_ORDER_STATUS_BYID = 'EDIT_ORDER_STATUS_BYID'